name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push하면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 컨테이너 종료 및 삭제
            docker stop backend || true
            docker rm backend || true

            # 최신 이미지 가져오기
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

            # 새 컨테이너 실행
            docker run -d --name backend -p 8080:8080 --restart always \
              -e SPRING_PROFILES_ACTIVE=production \
              ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
